## defaults for _all_ profiles
[default]
address = "127.0.0.1"
port = 8080
limits = { form = "64 kB", json = "1 MiB" }

## set only when compiled in release mode, i.e, `cargo build --release`
[release]
address = "0.0.0.0"
ip_header = false